name: CMake

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    
  
    steps:
      
    - uses: actions/checkout@v2
    
    - name: check
      run: ls -la
    

    - name: Go to bidirectionallist folder
      run: |
        cd bidirectional\ list
    
    - name: check
      run: ls 
    
    - name: mkdir build
      run: mkdir build
    
    - name: check
      run: ls -la 
    
  
