name: CMake

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    
  
    steps:
    - name: Show current folder
      run: ls -la
      
    - uses: actions/checkout@v2

    - name: Create build folder
      run: |
        cd bidirectional\ list
        mkdir build
        cd build
        
    - name: Configure cmake
      run: cmake ..
    
    - name: Build
      run: cmkae --build .
  
